### ISSUE TITLE
I have lots of unread messages

### ISSUE THREAD

**Issue by Noitidart** [inbasic/ignotifier#201]
I leave a lot messages unread, so it's just 9999 on the labels for me.

![gmailnotifier9999](https://cloud.githubusercontent.com/assets/6372489/2903822/1730eb3a-d5f5-11e3-9be4-445fa295a600.PNG)

Is there anyway after some time that it realizes i dont want to open those messages and it goes away?

**Comment by ajunayed** [comment]
Is there any solution to this problem? Thanks

**Comment by Noitidart** [comment]
Not that I found :(

**Comment by inbasic** [comment]
Actually it is possible through Gmail filters along with a Google App Script.

### Gmail filter setup
1. Search `newer_than:2d` in Gmail searchbox
2. Now press the down arrow and click on `Create filter from this search`
3. On the next screen, select `Apply the label:` and assign it to `recent` label (you need to make a new label with the exact same name as we use the label name later on)

So basically all new emails go to the label `recent` from now on. The only problem here is Gmail is not removing the label for old emails. We need to use a Google App script for removing the labels after custom time period.

### Google App Script Setup
1. Go to Google Docs
2. Click on New > More > Google App Script
3. Paste the following code in the editor
```javascript
function recent () {
  var delayDays = 7; // Enter # of days
  var maxDate = new Date();
  maxDate.setDate(maxDate.getDate()-delayDays);
  
  var label = GmailApp.getUserLabelByName("recent");
  var threads = label.getThreads();
  for (var i = 0; i < threads.length; i++) {
    if (threads[i].getLastMessageDate() < maxDate) {
      threads[i].removeLabel(label);
      Utilities.sleep(1000);
    }

  }
}
```
4. Press `Save` and assign a name for the script
5. Now on the `Run` menu, press `recent` to make sure the function works fine.
6. If it works, now you can set a tiger for the function. Go to `Resources` menu -> `Current Project Triggers` and setup a trigger. Here is mine,
![screen shot 2015-04-13 at 10 29 30](https://cloud.githubusercontent.com/assets/351062/7110522/4ba36c5a-e1c8-11e4-9af6-4c12ccd9e0d5.png)

This script removes the label `recent` from threads older than 7 days.

Now setup your Gmail Notifier to notify you about your `recent` label rather than `inbox`.

Note: You can play with the Gmail filter more to adjust it based on your needs.

**Comment by SoSick88** [comment]
Hey just want to say thanks.Was just wondering if you knew the safest way to keep passwords? I'm a little sceptic on having all passwords in one place! Anywas I'm off for the night so no rush, thnx again
