### ISSUE TITLE
Shorten the Firefox Toolbar Button Description

### ISSUE THREAD

**Issue by tomishere** [inbasic/ignotifier#306]
I like Gmail Notifier but the toolbar button in firefox is too lengthy. 
Gmail Notifier (restartless) My full email address  (#)
[screenshot](https://cloud.githubusercontent.com/assets/11354006/6530638/336fa880-c3f8-11e4-807b-b2164680b2b4.jpg)

Is way too many characters. Is there a way to shorten it to just 
Gmail Notifier (#) ?

**Comment by inbasic** [comment]
Are you using https://addons.mozilla.org/en-US/firefox/addon/classicthemerestorer/?

**Comment by tomishere** [comment]
I was - I uninstalled it two Firefox versions ago. I just reinstalled at your prompt and removed notifier in favor of the Gmail button. Notifier still works according to my taskbar icons but # of emails don't show on the button anymore. However, I viewed my emails and no new emails have came in since the restart.

Should I keep the restartless add-on? 
I do like the notification on my taskbar. In the past I used google talk but that went away. Google talk notified me whether my browser was open or not. Let m,e give this a day or two but as far as I can see, Your solution has fixed this issue. I will comment further if the issue is not fixed. Close this in two day and Thanx

**Comment by inbasic** [comment]
Well, I just wanted to point that the issue you reported about the toolbar button label in firefox is too lengthy is because of the Classic Theme Restorer extension. If you uninstall it, the label issue will be fixed.

> I do like the notification on my taskbar. In the past I used google talk but that went away. Google talk notified me whether my browser was open or not.

Unfortunately, the notifier cannot work when the browser is not running, however, you can keep the browser open in system tray using an extension like https://addons.mozilla.org/en-us/firefox/addon/minimizetotray-revived/
