### ISSUE TITLE
Blank notifications in Firefox

### ISSUE THREAD

**Issue by plasticlove** [inbasic/ignotifier#307]
I get this when I click the icon:
![image](https://cloud.githubusercontent.com/assets/11429034/6603882/fe027674-c824-11e4-9360-8b39afef5187.png)

Same issue in 0.5.3b2 and 0.5.2.1.

Firefox 36.0.1.

**Comment by inbasic** [comment]
First restart your browser, now open the Error console (Ctrl+Shift+J) and see if you get any relevant error in the console. How about when the popup is opened, any new errors?

**Comment by plasticlove** [comment]
When popup is opened:


![](http://i.imgur.com/r2m2DTH.png)

**Comment by inbasic** [comment]
Got it. Is it fixed on the latest beta,
https://addons.mozilla.org/firefox/downloads/file/303670/gmail_notifier_restartless-0.5.3b4-fx.xpi?src=devhub

**Comment by plasticlove** [comment]
Working. Thanks!

**Comment by inbasic** [comment]
Great!

**Comment by lililya** [comment]
Hello, my system is sound waves, I think I can not complete your request, please forgive me.
Hello, my system is sound waves, I think I can not complete your request, please forgive me.
Hello, my system is sound waves, I think I can not complete your request, please forgive me.
Hello, my system is sound waves, I think I can not complete your request, please forgive me.


lililya521@outlook.com
 
From: InBasic
Date: 2015-03-15 01:15
To: inbasic/ignotifier
Subject: Re: [ignotifier] Blank notifications in Firefox (#307)
Closed #307.

**Comment by lililya** [comment]
Because I do not know English, you do not talk, do not send e-mail over a few words, there is only one link, I think you want me to do, please help me, please indicate what the message meant.
Now you mean to call me all the signals fully closed yet?



lililya521@outlook.com
 
From: plasticlove
Date: 2015-03-15 00:33
To: inbasic/ignotifier
Subject: Re: [ignotifier] Blank notifications in Firefox (#307)
When popup is opened:
