### ISSUE TITLE
System Notification Icon Won't Go Away

### ISSUE THREAD

**Issue by JDKukis** [inbasic/ignotifier#345]
I've tried everything to hide the system notification icon. I've unchecked the box that's "supposed" to hide it, but seems to do nothing. I also, did the same within the Windows 10 settings and still it's there. I've reinstalled the app and it still won't go away. I've tried it on other computers and OSs and it won't hide. Please help.

**Comment by andreipoe** [comment]
I'd like to get rid of this as well. I don't remember it being there before, but now there's no way to remove it.

**Comment by Lunatrius** [comment]
I've tracked it down to the [`only-firefox`](https://github.com/inbasic/ignotifier/search?utf8=%E2%9C%93&q=%22only-firefox%22) class (Firefox version is missing the override). You can remove the tray icon by creating a new boolean property in `about:config`:
Name: `extensions.jid0-GjwrPchS3Ugt7xydvqVK4DQk8Ls@jetpack.show`
Value: `false`

I suggest disabling the extension before adding the value, otherwise you'll have to restart the browser after you add the value.

**Comment by inbasic** [comment]
Is this fixed on the latest release?

**Comment by andreipoe** [comment]
I can confirm that the taskbar icon is gone, and there is now a tickbox on the Settings page to activate it. Thanks!
