### ISSUE TITLE
Gmail Notifier Will Read your browsing History

### ISSUE THREAD

**Issue by binarybum** [inbasic/ignotifier#348]
Removed when I saw this.  Not a good idea to push updates like this without a good explanation or option to disable aggressive permissions.

**Comment by inbasic** [comment]
Gmail notifier needs to access to your storage API to save your preferences. This is noting new! It has been there since the first release!

https://developer.chrome.com/extensions/storage
https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/manifest.json#L11

**Comment by itsbenweeks** [comment]
Seconded. The version number is also inconsistent with the manifest file's version number in the above link to the source.

**Comment by inbasic** [comment]
Guys in Opera and Chrome to be able to store user preferences, the extension needs to have access to the [storage API](https://developer.chrome.com/extensions/storage). GN used to resort to `localStorage` but since this API is not permanent, the new version uses the standard storage API and hence needs the new permission. 

@itsbenweeks you can check the actual installed extension http://stackoverflow.com/questions/14543896/where-does-chrome-store-extensions. The one in GitHub is the multi-browser version for testers and developers. The one that is in Google Store is the browser specific version.

**Comment by itsbenweeks** [comment]
Thanks, @inbasic. Looking at the source, it is the storage api as you mention.
