### ISSUE TITLE
Gmail Notifier

### ISSUE THREAD

**Issue by Chino70** [inbasic/ignotifier#443]
When I close Firfox, my Gmail accounts disappear in, how do I save the accounts to open every day?

**Comment by inbasic** [comment]
You must have changed your Firefox settings to not store cookies. For 
this extension to work across sessions you need to allow cookies.

**Comment by Chino70** [comment]
Perfect, I'll try, thank you

**Comment by inbasic** [comment]
The minimum required cookies (thanks to Wisam comment)

![image](https://user-images.githubusercontent.com/351062/39403706-bb52d6ba-4b71-11e8-91e2-205010325085.png)

**Comment by CommanderBond** [comment]
Since Firefox was upgraded to 58b3, this fix does not work anymore. It seems to be related to First Party Isolation (privacy.firstparty.isolate = true). FF 57 with FPS worked well, but with FF 58b3 Gmail Notifier is always disconnected and asks to log in to the account upon refresh. However, Gmail starts already loggeed in. 
Maybe they changed something in FF 58b3 concerning FPS that causes Gmail Notifier to break?
