### ISSUE TITLE
Not compatible with First Party isolation on Firefox?

### ISSUE THREAD

**Issue by EchoDev** [inbasic/ignotifier#505]
It doesn't seem like Gmail notifier is compatible with first party isolation on Firefox. Is this correct?

Steps to reproduce:

1. Delete Gmail and Google related cookies
2. Enable first party isolation
3. Log in to Gmail
4. Gmail notifier should work but it doesn't

**Comment by inbasic** [comment]
Correct. This extension fetches Gmail feeds like https://mail.google.com/mail/u/0/feed/atom/inbox every 15 minutes by default to get the number of unread emails. When this cookie isolation is enabled, the extension fetches the feed without the cookies being sent which is equal to not be logged-in. So if FF provides a way to whitelist this extension it should work, otherwise you need to use an extension to block third-party cookies (extension-level blocking does not have the power to block other extensions)
