### ISSUE TITLE
Disable/unwatch account

### ISSUE THREAD

**Issue by semenmiroshnichenko** [inbasic/ignotifier#549]
I have 2 google account, the private one and the work one. For a work account I have sync with outlook, so I want to watch only for new emails in my private account. But I want to still be logged in my work account so I can access other google services with this account.

How can I achieve that?

**Comment by roos22** [comment]
Hi, did you get a reply for this?  I have the same problem

**Comment by semenmiroshnichenko** [comment]
@roos22 Not yet. It looks like this project is not maintained anymore, have many open issues and old and not closed PRs.

**Comment by RobotManager** [comment]
I seem to have found a way to get it to work.  

It's similar to how it's explained in the FAQ, only instead of removing "inbox" I manually typed "inbox" into each account I wanted to include in notifier and I typed "none" into the account I didn't want to include.  Since I don't have a label called "none" it effectively eliminates any e-mails from showing up for that account.  Hope that helps.

**Comment by semenmiroshnichenko** [comment]
That is a solution for me, very clever trick!
