### ISSUE TITLE
Getting "Unexpected Error:: doc.querySelector(...)is null" (v3 edition for Firefox)

### ISSUE THREAD

**Issue by helil** [inbasic/ignotifier#573]

**Comment by inbasic** [comment]
Open the browser console (Ctrl + Shift + J) and try to regenerate the error. Do you get more useful info in the console?

**Comment by micander** [comment]
I had this issue and receive these messages in the browser console. The cause was that the session on one of my accounts had expired. In my opinion this is definitely a situation that deserves to be handled gracefully with a message to the user and a skip of the affected account.

`1626687126953	addons.webextension.{ea07a25b-ce2e-4084-8efe-a633f48cda88}	WARN	Loading extension '{ea07a25b-ce2e-4084-8efe-a633f48cda88}': Reading manifest: Warning processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.`
`XHRGET https://mail.google.com/mail/u/6/feed/atom/inbox
[HTTP/2 401 Unauthorized 208ms]

GET https://mail.google.com/mail/u/6/feed/atom/inbox
Status401
Unauthorized
VersionHTTP/2
Transferred587 B (147 B size)
Referrer Policystrict-origin-when-cross-origin
    alt-svc
    	clear
    cache-control
    	private, max-age=0
    content-encoding
    	gzip
    content-length
    	121
    content-security-policy
    	frame-ancestors 'self'
    content-type
    	text/html; charset=UTF-8
    date
    	Mon, 19 Jul 2021 09:32:11 GMT
    expires
    	Mon, 19 Jul 2021 09:32:11 GMT
    server
    	GSE
    www-authenticate
    	BASIC realm="mail.google.com"
    x-content-type-options
    	nosniff
    X-Firefox-Spdy
    	h2
    x-frame-options
    	SAMEORIGIN
    x-xss-protection
    	1; mode=block
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Cookie
    	GMAIL_AT=<snip>; COMPASS=gmail=<snip>; __Secure-OSID=<snip>; __Host-GMAIL_SCH_GMN=1; __Host-GMAIL_SCH_GMS=1; __Host-GMAIL_SCH_GML=1; __Host-GMAIL_SCH=nsl; S=<snip>; S=billing-ui-v3=<snip>
    DNT
    	1
    Host
    	mail.google.com
    TE
    	Trailers
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0`

**Comment by inbasic** [comment]
@micander thanks for the log. This issue should be fixed by the new release.
